apiVersion: v1
kind: Service
metadata:
  name: {{ include "recurring-task-service.fullname" . }}
  labels:
    {{- include "recurring-task-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "recurring-task-service.selectorLabels" . | nindent 4 }}